### PR TITLE
Use ruma-api-macros for more endpoints

### PR DESCRIPTION
**Pull request by jplatte**
I saw today that you had converted the membership modules, which I had already done before on my fork. So to avoid any additional duplication of work, here is a PR for what me and @rschulman have converted so far. (I took out the commit for the membership module though, that would probably just result in merge conflicts)

### CODE REVIEW

**Comment by jplatte** [comment]
I'll rewrite some stuff, the change to use my fork of ruma-api-macros is pointless.

**Comment by jplatte** [comment]
Actually, ruma-api needs to be updated for this to work out properly. At least I can't see how the current ruma-api-macros (where my changes are already present) would work with the current (as in, current in the GitHub ruma org) ruma-api. I've squashed my changes to ruma-api and pushed them to [my fork](https://github.com/jplatte/ruma-api) again. I'll push an updated version of this PR in a second, which relies on that one commit from my ruma-api fork being present in ruma/ruma-api. So if you do a fast-forward of that, this PR should be merge-able. Sorry for the inconvenience!

**Comment by jplatte** [comment]
I should have done this two days ago.. Just realized that you have actually made the necessary changes on ruma-api. Force-pushed another version without any changes to `Cargo.toml`.

**Comment by jimmycuadra** [comment]
Muchas gracias!

**Pull request merged**
