### PR TITLE
Add filter optional query param to /messages (r0.3.0 compatibility)

### PR DESCRIPTION
**Pull request by adevore**

### CODE REVIEW

**Comment by adevore** [comment]
There is a transitive dependency on smallvec 1.0, which cannot build on Rust versions below 1.36 due to use of MaybeUninit and liballoc. Both were stabilized in that release. Unless there is a clear use case for an older version of the compiler, maybe it would be best to up the requirements?

**Comment by jplatte** [comment]
Yes, I have seen this in ruma-api where it also caused CI failure. Since realistically almost everyone using this crate will use async / await and thus require Rust >= 1.39, I'm fine with bumping or MSRV here.

**Comment by jplatte** [comment]
I've bumped the MSRV on master, you just need to rebase. Also, can you add a changelog entry for the change you made? :)

**Comment by jplatte** [comment]
Thanks!

**Pull request merged**
