### PR TITLE
Change Device fields according to the spec

### PR DESCRIPTION
**Pull request by gnieto**
Fields `ip` and `last_seen` should be named `last_seen_ip` and
`last_seen_ts` according to the spec.

https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-devices

### CODE REVIEW

**Comment by jplatte** [comment]
Thanks! Could you add a changelog entry for this under bug fixes?

@iinuwa any idea why these were added with the wrong names to begin with?

**Comment by iinuwa** [comment]
Nope. That was one of the first endpoints I did, so I probably just didn't know what I was doing. XD

**Comment by gnieto** [comment]
@jplatte Done

**Comment by jplatte** [comment]
Thanks again!

**Pull request merged**
